# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rune < Formula
  desc "AI-powered Git commit message generator"
  homepage "https://github.com/sidkhuntia/rune"
  version "1.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sidkhuntia/rune/releases/download/v1.0.16/rune-darwin-amd64.tar.gz"
      sha256 "2f1345bf15d9b3dbed4989b291764f0db0a7ce737349d1c83023eca8f2bc1dfa"

      def install
        bin.install "rune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sidkhuntia/rune/releases/download/v1.0.16/rune-darwin-arm64.tar.gz"
      sha256 "0315add04b029fbc78986764877825072d2cdd743cfb917ce4545d939f341061"

      def install
        bin.install "rune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/rune/releases/download/v1.0.16/rune-linux-amd64.tar.gz"
      sha256 "058506bbd9a3eb85cf6fdbb98be412b8e7ca35338f929833569b40f7ced80b74"
      def install
        bin.install "rune"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sidkhuntia/rune/releases/download/v1.0.16/rune-linux-arm64.tar.gz"
      sha256 "c061591a74dcf30e9589482813bea9e4dadb3b3168885d28458e8fba600c4e04"
      def install
        bin.install "rune"
      end
    end
  end

  head "https://github.com/sidkhuntia/rune.git"

  test do
    system "#{bin}/rune --help"
  end
end
